# Generated by Django 3.2 on 2021-04-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('code', models.CharField(max_length=200, verbose_name='Kode Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Nama Perusahaan')),
                ('contact_person', models.CharField(max_length=200)),
                ('address', models.TextField(verbose_name='Alamat')),
                ('city', models.CharField(max_length=200, verbose_name='Kota')),
                ('provinz', models.CharField(max_length=200, verbose_name='Provinsi')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('terms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefon')),
                ('starting_date', models.DateField(blank=True, null=True, verbose_name='Mulai Kerja')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
