# Generated by Django 3.2 on 2021-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='starting_date',
            field=models.DateField(blank=True, default='28/04/2021', null=True, verbose_name='Mulai Kerja'),
        ),
    ]
