# Generated by Django 3.2 on 2021-04-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_metric',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Satuan Unit (M, KG)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='metric_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ukuran'),
        ),
    ]
