# Generated by Django 3.2 on 2021-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
