# Generated by Django 3.2 on 2021-05-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210502_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'verbose_name': 'Surat Jalan'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.product'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='web.deliveryorder', verbose_name='Surat Jalan'),
        ),
    ]
