# Generated by Django 3.2 on 2021-05-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210509_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pic',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
