# Generated by Django 3.2 on 2021-05-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_deliveryorder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon'),
        ),
    ]
