# Generated by Django 3.2 on 2021-05-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210526_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='web.category'),
        ),
    ]
