# Generated by Django 3.2 on 2021-05-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_deliveryorder_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='web.customer'),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='web.sales'),
        ),
    ]
